# specifying a CIDR for our cluster to use.
# can be basically any private range except for ranges already in use.
# apparently it isn't too hard to run out of IPs in a /24, so we're using a /22
pod_cidr: "10.16.0.0/22"
control_vip: "192.168.3.30"
control_port: "4200"

# this defines what the join command filename will be
join_command_master_location: "join_command_master.out"
join_command_worker_location: "join_command_worker.out"

# setting the home directory for retreiving, saving, and executing files
home_dir: "/home/debian"

