keepalived:
  master:
    state: MASTER
    interface: eth0
    router_id: 51
    priority: 101
    auth_pass: 42
    apiserver_vip: 192.168.4.31
  backup:
    state: BACKUP
    interface: eth0
    router_id: 51
    priority: 100
    auth_pass: 42
    apiserver_vip: 192.168.4.31

apiserver_vip: 192.168.4.31
apiserver_port: 4200
