# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
# https://github.com/virtualelephant/vsphere-kubernetes/blob/master/ansible/cilium-install.yml#L57

# ansible .yml files define what tasks/operations to run

---
- hosts: all # run on the "all" hosts category from ansible-hosts.txt
  # become means be superuser
  become: true
  remote_user: debian
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: create keyrings directory
    file:
      path: /etc/apt/keyrings
      state: directory

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release | lower }} stable
      state: present

  - name: Install docker and its dependecies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: verify docker installed, enabled, and started
    service:
      name: docker
      state: started
      enabled: yes

  - name: Ensure containerd is started and enabled at boot.
    service:
      name: containerd
      state: started
      enabled: yes

  - name: create Containerd directory
    file:
      path: /etc/containerd
      state: directory

  - name: Get defaults from containerd.
    command: containerd config default
    changed_when: false
    register: containerd_config_default

  - name: Prepare containerd/config.toml from default config
    copy:
      dest: /tmp/containerd_config.toml
      content: "{{ containerd_config_default.stdout }}"
    changed_when: false

  - name: Set Cgroup driver to systemd
    lineinfile:
      insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
      line: '          SystemdCgroup = true'
      state: present
      path: /tmp/containerd_config.toml
    changed_when: false

  - name: Make sure  SystemdCgroup = false is not set
    ansible.builtin.lineinfile:
      path: /tmp/containerd_config.toml
      state: absent
      line: '            SystemdCgroup = false'
    notify: restart containerd
    changed_when: false

  - name: Copy config.toml to /etc/containerd
    copy:
      remote_src: true
      src: /tmp/containerd_config.toml
      dest: /etc/containerd/config.toml

  - name: Cleanup temporary file
    file:
      path: /tmp/containerd_config.toml
      state: absent
    changed_when: false

  - name: Ensure containerd is restarted immediately if necessary.
    meta: flush_handlers

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb >= 0

  - name: Add an apt signing key for Kubernetes
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
      mode: '0644'
      force: true


  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
      state: present
      filename: kubernetes

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        # it is usually recommended to specify which version you want to install
        - kubelet
        - kubeadm
        - kubectl

  - name: hold kubernetes binary versions (prevent from being updated)
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    loop:
      - kubelet
      - kubeadm
      - kubectl

# this has to do with nodes having different internal/external/mgmt IPs
# {{ node_ip }} comes from vagrant, which I'm not using yet
#  - name: Configure node ip -
#    lineinfile:
#      path: /etc/default/kubelet
#      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Ensure kubelet is started and enabled at boot.
    service:
      name: kubelet
      state: started
      enabled: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: add debian user to docker
    user:
      name: debian
      group: docker

  - name: reboot to apply swap disable
    reboot:
      reboot_timeout: 180 #allow 3 minutes for reboot to happen
