- hosts: kube_server
  become: true
  remote_user: debian

  tasks:
  - name: Create target directory
    become: yes
    become_user: root
    file:
      path: '/tmp/k9s'
      state: directory
      mode: '0755'

  - name: download k9s tarball
    become: yes
    become_user: root
    unarchive:
      src: https://github.com/derailed/k9s/releases/download/v0.26.7/k9s_Linux_x86_64.tar.gz
      dest: "/tmp/k9s"
      remote_src: yes

  - name: copy k9s binary
    become: yes
    become_user: root
    copy:
      src: "/tmp/k9s/k9s"
      dest: /usr/local/bin/
      remote_src: true
      mode: '0755'
